apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: daves125125/kubernetes-monitoring-sample:latest
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: web
          readinessProbe:
            periodSeconds: 5
            httpGet:
              path: /health
              port: web
