apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  ports:
  - name: service-web
    port: 8012
    targetPort: web
    protocol: TCP
  selector:
    app: sample-app
