apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: sample-team
  version: v1.7.1
  resources:
    requests:
      memory: 400Mi
