apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  serviceMonitorSelector:
    matchLabels:
      tier: monitor
  resources:
    requests:
      memory: 400Mi
  