apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
    tier: monitor
spec:
  selector:
    matchLabels:
      prometheus: k8s
  endpoints:
  - port: web
    interval: 30s
